version: '3.7'
services:
  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins
    restart: always
    environment:
      - TZ=Asia/Shanghai
    ports:
      - '10086:8080'
      - '50001:50000'
    volumes:
      - /srv/jenkins-data:/var/jenkins_home:z
      - /srv/jenkins-data/docker.sock:/var/run/docker.sock
    network_mode: "bridge"