version: '3'
services:
  mysql8:
    image: mysql
    container_name: mysql8
    restart: always
    command:
      --default-authentication-plugin=mysql_native_password
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_general_ci
      --explicit_defaults_for_timestamp=true
      --lower_case_table_names=1
    volumes:
      - /apps/docker/data/mysql/mysql8/lib/mysql:/var/lib/mysql
    env_file:
      - .env
    ports:
      - 3306:3306

